### ISSUE TITLE
Create design storyboard/mockup

### ISSUE THREAD

**Issue by JawadHossain** [CMPUT404F21TEAM/social-distribution#11]
We could consider using Figma where we can all edit design together. Similar to google docs.

**Comment by JawadHossain** [comment]
https://www.figma.com/file/4V0nM5Zv7Zb3c8Mt4BMW3P/SocialDistributionMockUps?node-id=0%3A1
We can use this to come up with UI mockups. Added two pages. Feel free to tweak the design or add pages!

**Comment by olivier-vadiaval** [comment]
## I added 4 more mockups:
### (Was already there but was empty) HomePage./
- Shows all public posts

### HomePage./Post1
- Shows post detail (in this case Post1)
- Details include: post comments and likes
- Allows author to like, comment and (re-)share post

### HomePage./Post1/WriteComment
- Allows author to write and post a comment

### HomePage./Post1/ReShare
- Allows author to share posts with other authors
- Uses an overlay, that's why background appears lighter in color

**Comment by olivier-vadiaval** [comment]
# I added mockups for editing and deleting a post.

## Editing:
- Author must click on three dots ("⋮") in the top-right corner of the post. 3 options slide down: edit, flag, delete
- Author clicks on edit option (stylus icon)
- Overlay opens and author can edit visibility, any attached image and text.

## Delete
- Author clicks on three dots and select delete option.
- Author clicks "Delete" or "Cancel"

**Comment by olivier-vadiaval** [comment]
## Added mockups for author profiles + edit option

### Author Profile
- If author is current user, the latter can edit his/her profile, see inbox, see posts (sort them as well) and write a post.
- If author is not current user, the latter can see that author's posts (sort them as well) and befriend them

### Editing Author Profile
- Editing author profile uses overlay (as for posts).
- Can change photo, username, email, password.
- Can remove photo (click the (x) over the photo)

**Comment by tylerelston** [comment]
- Added inbox page, not sure if we just want these notifications to appear in the app's mainpage though
- Added create post pages
