### ISSUE TITLE
Fix Create Form screen

### ISSUE THREAD

**Issue by debecerra** [CMPUT404F21TEAM/social-distribution#158]
Create Post form takes an image, but that image is never sent out as a post due to the constraints of the Post API JSON specifications. Changes are needed to enforce that a Post is either just an image or markdown that may have an embedded image (URL to an image saved elsewhere). 

OR we create two posts if an author wants to attach an image, an Image Post and a Markdown Post.

Either way, the Post cannot contain both an image base64 AND markdown/text.

**Comment by olivier-vadiaval** [comment]
For embedded images in markdown, should we still send out the image?
In #172, the user can only create an image post or a text/md post and content is stored in a binary field in the db.

**Comment by debecerra** [comment]
I think we should not send out image posts, and all image posts should be unlisted. What does everyone else think? They don't need the image post. They just need the image URL which is already in the markdown.

**Comment by olivier-vadiaval** [comment]
Yup, I agree. If their markdown-related code works correctly, they should get the post image eventually. Currently, if the request created by their markdown-parsing code contains the 'image/webp' mime-type when getting an embedded image, they get back the post image in webp format. If they want the post, they can exclude that mime-type and make a regular GET for that post. We then need to return the post object in json instead of the image in webp format. Of course, we need to check the visibility of the post as well.

Also, the reason I'm returning webp is because the markdown parsing code that we use only displays the image when it's webp. I tried with other formats (png, jpg), but it didn't work.

But, yeah, in a nutshell, if it's embedded, we don't send it by creating a disposable post.
