### ISSUE TITLE
Host field of json sent to remote inbox not set

### ISSUE THREAD

**Issue by JawadHossain** [CMPUT404F21TEAM/social-distribution#262]
A local json body sent to remote inbox. 
{
   "type":"post",
   "title":"test",
   "id":"http://127.0.0.1:8000/api/author/78dd7080-87c2-4e5e-bee7-ae0349e6840a/posts/b903b645-58f4-4e2e-9700-a6658c706a2a",
   "source":"http://127.0.0.1:8000/api/author/78dd7080-87c2-4e5e-bee7-ae0349e6840a/posts/b903b645-58f4-4e2e-9700-a6658c706a2a",
   "origin":"http://127.0.0.1:8000/api/author/78dd7080-87c2-4e5e-bee7-ae0349e6840a/posts/b903b645-58f4-4e2e-9700-a6658c706a2a",
   "description":"asdf",
   "contentType":"text/plain",
   "content":"",
   "author":{
      "type":"author",
      "id":"http://127.0.0.1:8000/api/author/78dd7080-87c2-4e5e-bee7-ae0349e6840a",
      "host":"",
      "displayName":"Jawad Hossain",
      "url":"http://127.0.0.1:8000/api/author/78dd7080-87c2-4e5e-bee7-ae0349e6840a",
      "github":"",
      "profileImage":""
   },
   "categories":[
      
   ],
   "count":0,
   "comments":"http://127.0.0.1:8000/api/author/78dd7080-87c2-4e5e-bee7-ae0349e6840a/posts/b903b645-58f4-4e2e-9700-a6658c706a2a/comments/",
   "commentsSrc":{
      "type":"comments",
      "page":1,
      "size":5,
      "post":"http://127.0.0.1:8000/api/author/78dd7080-87c2-4e5e-bee7-ae0349e6840a/posts/b903b645-58f4-4e2e-9700-a6658c706a2a",
      "id":"http://127.0.0.1:8000/api/author/78dd7080-87c2-4e5e-bee7-ae0349e6840a/posts/b903b645-58f4-4e2e-9700-a6658c706a2a/comments",
      "comments":[
         
      ]
   },
   "published":"2021-12-02T20:42:17.609106+00:00",
   "visibility":"PUBLIC",
   "unlisted":false
}

**Comment by debecerra** [comment]
This is due to the recent update. Pls edit (don't need to change anything) and save your profile and it should be fixed. I tried to do this for all models but the admin panel was forcing me to fill out the follow requests field and wouldn't let me save without that. Regardless, we can go through the admin panel and manually save all authors if needed. 

This is only for existing authors. All new authors will have the host set when they are saved the first time.
